build:
	@ echo -e "\nStart building Lazy module...\n"
	@ dotnet build

repl:
	@ echo -e "\nStart Lazy interactive session...\n"
	@ fsharpi ../Base/Common.fs ../Base/Combinator.fs ../Base/Int.fs ../Base/Bool.fs ../Base/List.fs ../Base/String.fs \
Lazy.fs

