build:
	@ echo -e "\nStart building ParserCombinators module...\n"
	@ dotnet build

repl:
	@ echo -e "\nStart ParserCombinators interactive session...\n"
	@ fsharpi ../Base/Common.fs ../Base/Combinator.fs ../Base/Int.fs ../Base/Bool.fs ../Base/List.fs ../Base/String.fs \
Types.fs Combinators.fs Grammar.fs Lexer.fs Parser.fs Interpret.fs

