build:
	@ echo -e "\nStart building BinTree module...\n"
	@ dotnet build

repl:
	@ echo -e "\nStart BinTree interactive session...\n"
	@ fsharpi ../Base/Common.fs ../Base/Combinator.fs ../Base/Int.fs ../Base/Bool.fs ../Base/List.fs ../Base/String.fs \
../CharPics/CharPics.fs BinTree.fs

