build:
	@ echo -e "\nStart building GameOfLife module...\n"
	@ dotnet build

repl:
	@ echo -e "\nStart GameOfLife module interactive session...\n"
	@ fsharpi ../Base/Common.fs ../Base/Combinator.fs ../Base/Int.fs ../Base/Bool.fs ../Base/List.fs ../Base/String.fs \
../CharPics/CharPics.fs GameOfLife.fs

