build:
	@ echo -e "\nStart building Base module...\n"
	@ dotnet build

repl:
	@ echo -e "\nStart Base module interactive session...\n"
	@ fsharpi Common.fs Combinator.fs Int.fs Bool.fs List.fs String.fs

