build:
	@ echo -e "\nStart building CharPics module...\n"
	@ dotnet build

repl:
	@ echo -e "\nStart CharPics module interactive session...\n"
	@ fsharpi ../Base/Common.fs ../Base/Combinator.fs ../Base/Int.fs ../Base/Bool.fs ../Base/List.fs ../Base/String.fs \
CharPics.fs

