build:
	@ echo -e "\nStart building IOMonad module...\n"
	@ dotnet build

repl:
	@ echo -e "\nStart IOMonad interactive session...\n"
	@ fsharpi ../Base/Common.fs ../Base/Combinator.fs ../Base/Int.fs ../Base/Bool.fs ../Base/List.fs ../Base/String.fs \
IOMonad.fs IOMonad2.fs MaybeIOMonad.fs

